# These are config values that users can set from the GUI or the commandline
options:
  metalogger-port:
    type: int
    default: 9419
    description: The client port
  chunkserver-port:
    type: int
    default: 9420
    description: The client port
  client-port:
    type: int
    default: 9421
    description: The client port
  tapeserver-port:
    type: int
    default: 9424
    description: The client port